### PR TITLE
fix(service-host): add file exists function to support node12 module resolution

### LINKED ISSUE #61: Module resolution NodeNext or Node12 seems to break import organization
Running with debug on I am getting an error about host.fileExists is not a function.

Repro [here](https://github.com/RtVision/prettier-organize-imports-repro)

Full error stack

```
TypeError: host.fileExists is not a function
    at getPackageJsonInfo (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:43802:37)                                                                                                                                                                                                                                            at Object.getPackageScopeForPath (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:43765:23)
    at lookupFromPackageJson (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:116492:28)
    at Object.getImpliedNodeFormatForFile (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:116486:200)
    at acquireOrUpdateDocument (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:136053:47)
    at Object.acquireDocumentWithKey (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:136030:20)
    at getOrCreateSourceFileByPath (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:165213:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:165160:24)
    at findSourceFileWorker (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:118302:29)
    at findSourceFile (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:118200:26)
```

### PR DESCRIPTION
**Pull request by kalvenschraut**
fixes #61 

Don't know if this is the preferred way to fix the issue just something I found quickly that did fix it in my case. Figured I would submit a quick PR in case it was.

### CODE REVIEW

**Comment by simonhaenisch** [comment]
Hey, #60 does some fixes for Vue and I'll get that merged soon (waiting for some feedback)... I would like to merge that first and see if it fixes your issue. If not, then we can revisit this (:

**Comment by kalvenschraut** [comment]
This specific PR and the issue that it is trying to fix is not vue specific and has a reproduction available on #61.

**Comment by simonhaenisch** [comment]
Ok thanks for the info. I'll have a look as soon as I have time.

**Comment by simonhaenisch** [comment]
See the commit mentioned above :point_up:, I've added `fileExists` and `readFile` to the language service host because TS was complaining about them missing after bumping the TypeScript version in dev dependencies. I used the `ts.sys` versions though, not sure about using the `fs` module directly.

**Pull request closed without merging**
