### PR TITLE
Upgrade to Volar v2

### LINKED ISSUE #98: Volar packages renamed
The volar packages have been renamed in https://github.com/vuejs/language-tools/pull/3134. It would be nice if the new vue/typescript package could be supported as well.

### PR DESCRIPTION
**Pull request by johnsoncodehk**
Fixes #98

### CODE REVIEW

**Comment by mreduar** [comment]
Thank you so much!

**Comment by simonhaenisch** [comment]
Thanks a lot for this @johnsoncodehk!

Only thing I'd like to discuss: why did you decide to change Vue support from optional peer deps to actual dependencies? I'd like to revert that to only `require` the vue stuff when `parser === 'vue'`, or is there a reason that wouldn't work anymore?

Reason is that I don't want to force people who don't use Vue to install extra deps `@volar/typescript` and `@vue/language-core` that they will never use. Also not sure about the performance impact of `require`'ing those extra packages (that's why they were only imported within the "is vue" enclosure).

**Comment by johnsoncodehk** [comment]
@simonhaenisch has changed to `vue-tsc` as a peer dependency.

**Comment by simonhaenisch** [comment]
Thanks! looks good to me now 🙏  I just need to find some time to actually publish this as a new major.

**Comment by simonhaenisch** [comment]
Published as `4.0.0` 🎉

**Comment by mreduar** [comment]
> Published as `4.0.0` 🎉

Thank you!

**Pull request merged**
